services:
  backend:
    build:
      context: ./
      target: backend-serve
    ports:
      - 3001:3001
  frontend:
    build:
      context: ./
      target: frontend-build
    ports:
      - 3000:3000